name: CI
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Menampilkan pesan
        run: echo "CI berhasil dijalankan!"
      - name: Melihat isi repository
        run: ls -la
      - name: menjalankan tes
        run: echo "Menjalankan tes unit..."